[tool.poetry]
name = "jm-crypto-ciphers"
version = "2.0.1"
description = "Implements various ciphers from the pycryptodome package and some custom ones."
authors = ["Jonathan Mahaffey"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
