[tool.poetry]
name = "pyautoinstall"
version = "0.0.1"
description = "Magically install modules just by importing them!!"
authors = ["Ajay Ratnam <ajayratnam.satheesh@gmail.com>"]
maintainers = ["Ajay Ratnam <ajayratnam.satheesh@gmail.com>"]
license = "MIT"
keywords = ["auto", "install", "import", "pip"]
homepage = 'https://github.com/ajratnam/pyautoinstall'
documentation = 'https://github.com/ajratnam/pyautoinstall'
repository = 'https://github.com/ajratnam/pyautoinstall'
readme = 'README.md'
classifiers = [
    "Development Status :: 1 - Planning",
    "Intended Audience :: Developers",
    "License :: OSI Approved",
    "License :: OSI Approved :: MIT License",
    "Natural Language :: English",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.9",
    "Topic :: Software Development",
    "Topic :: Software Development :: Libraries",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Software Development :: Version Control",
    "Topic :: Software Development :: Version Control :: Git",
    "Programming Language :: Python :: Implementation",
    "Programming Language :: Python :: Implementation :: CPython",
    "Topic :: Utilities",
]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
