[tool.poetry]
name = "pedroai"
version = "0.2.0"
description = ""
authors = ["Pedro Rodriguez <me@pedro.ai>"]

[tool.poetry.dependencies]
python = "^3.7"
plotnine = "^0.7"
requests = "^2.23.0"
pysimdjson = {extras = ["dev"], version = "^4.0.3"}
typer = "^0.4.0"
toml = "^0.10.2"
pydantic = "^1.7.3"
rich = "^10.15.2"
altair-saver = "^0.5.0"
altair = "^4.1.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
black = "^19.10b0"
pylint = "^2.4.4"
mypy = "^0.782"
isort = "^5.6.4"

[tool.poetry.scripts]
pedroai = "pedroai.main:cli"

[tool.isort]
known_first_party = "pedroai"
profile = "black"
multi_line_output = 3

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
