
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-12-09T16:14:26-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "88da5924f0faa5f0e0ba76e14b2161d13ead88a2",
 "version": "0.13.46"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
