[tool.poetry]
name = "the-social-network"
version = "0.0.4"
description = "Basic social network core."
authors = ["Marc Feger <marc.feger@hhu.de>"]
license = "BSD-4"
readme = "README.md"
homepage = "https://gitlab.cs.uni-duesseldorf.de/feger/the-social-network"


[tool.poetry.dependencies]
python = "^3.9"
Django = "^3.2.9"
djangorestframework = "^3.12.4"
Pillow = "^8.4.0"
django-cors-headers = "^3.10.0"
django-dotenv = "^1.4.2"
uWSGI = "^2.0.20"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
