
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-12-10T12:47:35+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "8271156abe352836b5e8778bd2776d901e610415",
 "version": "0.0.69"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
