
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-12-09T00:39:53+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "1a7d0f4c3960c098c1df8256ad97b5ae3c205188",
 "version": "3.0.0dev2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
