[tool.poetry]
name = "pm-attacher"
version = "0.2.2"
description = "Attach files to a patient's medical record (TrustMed)"
authors = ["Vladislav Chmelyuk <neimp@yandex.ru>"]
readme = "README.md"

[tool.poetry.scripts]
pm-attacher = "pm_attacher.main:app"

[tool.poetry.dependencies]
python = "^3.9"
pymssql = "^2.2.2"
loguru = "^0.5.3"
typer = "^0.4.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

