
[tool.poetry]
name = "music_organizer"
version = "0.1.1"
description = "Music files organizer"
authors = ["JOramas <javiale2000@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
typer = "^0.4.0"
audio-metadata = "^0.11.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[package]
include = ["/*.py"]