[tool.poetry]
name = "rawr-python"
version = "0.1.0"
description = "Python Riot API Wrapper"
authors = ["Ben Dowling <ben.dowling@icloud.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
pydantic = "^1.8.2"
boltons = "^21.0.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
