[tool.poetry]
name = "itchat2-uos"
version = "1.0.0"
description = ""
authors = ["aox.lei <2387813033@qq.com>"]
packages = [
    { include = "itchat" },
]

[tool.poetry.dependencies]
python = "^3.7"
requests = "^2.26.0"
PyQRCode = "^1.2.1"
pypng = "^0.0.21"

[tool.poetry.dev-dependencies]
autopep8 = "^1.6.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
