[tool.poetry]
name = "high-order-layers-torch"
version = "1.1.1"
description = "High order layers in pytorch"
authors = ["jloverich <john.loverich@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9"
torch = "*"
pytorch-lightning = "*"
torchmetrics = "^0.6.1"

[tool.poetry.dev-dependencies]
pbr = "*"
hydra-core = "*"
matplotlib = "*"
torchvision = "*"
pytest = "*"
torch-optimizer = "^0.1.0"
black = {version = "^21.11b1", allow-prereleases = true}
torchmetrics = "^0.6.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
