[dependencies]
pythonize = "0.15"

[dependencies.pyo3]
features = ["extension-module"]
version = "0.15"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
features = ["preserve_order"]
version = "1"

[dependencies.telemetry-parser]
path = "local_dependencies/telemetry-parser"

[lib]
crate-type = ["cdylib"]
name = "telemetry_parser"
path = "python-module.rs"

[package]
authors = ["Adrian <adrian.eddy@gmail.com>"]
edition = "2018"
name = "telemetry-parser-py"
version = "0.1.8"
