[build-system]
requires = [
    "setuptools>=50",
    "wheel"
]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 79
target-version = ['py39']
include = '\.pyi?$'
exclude = '(\.git)'
indent_size=4