[tool.poetry]
name = "blender-basico"
version = "0.2.2rc0"
description = "Django shared app, featuring essential components for blender.org sites."
authors = ["Francesco Siddi <francesco@blender.org>"]

[tool.poetry.dependencies]
python = ">=3.6,<4.0"
django = "^2.1"
libsasscompiler = "^0.1.5"
jsmin = "^3.0.0"
pypugjs = "^5.9.8"
django-pipeline = "^2"

[tool.poetry.dev-dependencies]

[tool.poetry.scripts]
update-bwa = "tools:update"
[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

