- args:
  - git-hook
  - pre-commit
  entry: dvclive
  id: dvclive-pre-commit
  language: python
  language_version: python3
  name: dvclive pre-commit
  require_serial: true
  stages:
  - commit
  verbose: true