[tool.poetry]
authors = ["Marcelo Moreira G Silva <mqestatistico@gamil.com>"]
description = "Convert csv to json or convert json to csv. Publishing only for learning purpose at PUC-MG. DS Class"
name = "mmoreira_csv_converter"
readme = "readme.md"
version = "0.2.0"

[tool.poetry.dependencies]
click = "^8.0.3"
flake8 = "^4.0.1"
python = "^3.9"

[tool.poetry.dev-dependencies]
black = "^21.9b0"
click = "^8.0.3"
flake8 = "^4.0.1"
ipython = "^7.28.0"
isort = "^5.9.3"
mypy = "^0.910"
pathlib = "^1.0.1"
pytest = "^6.2.5"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]

[tool.poetry.scripts]
csv2json = 'mmoreira_csv_converter.csv2json:converter'

[tool.black]
line-length = 99

[tool.isort]
profile = "black"
