exclude: .*?/migrations/.*?
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.0.0    # Use the ref you want to point at
  hooks:
  - id: flake8
    entry: pflake8
    additional_dependencies: [flake8-tidy-imports, flake8-mutable, pyproject-flake8]
    args: [--count, --show-source]
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-merge-conflict
  - id: check-yaml
- repo: https://github.com/asottile/pyupgrade
  rev: v2.29.1
  hooks:
  - id: pyupgrade
    args: [--py36-plus]
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.2.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2']
- repo: https://github.com/ambv/black
  rev: 21.11b1
  hooks:
  - id: black
- repo: https://github.com/PyCQA/pydocstyle
  rev: 6.1.1
  hooks:
  - id: pydocstyle
    files: ^src/
    args:
    - --ignore=D104, D100, D2, D4
    - --count
- repo: https://github.com/hadialqattan/pycln
  rev: v1.1.0
  hooks:
  - id: pycln
    args: [--config=pyproject.toml]
