# coding: utf-8

"""
    Klaviyo API

    Empowering creators to own their destiny  # noqa: E501

    OpenAPI spec version: 2021.11.26
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.metric_export import MetricExport  # noqa: E501
from swagger_client.rest import ApiException


class TestMetricExport(unittest.TestCase):
    """MetricExport unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMetricExport(self):
        """Test MetricExport"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.metric_export.MetricExport()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
