# coding: utf-8

"""
    Klaviyo API

    Empowering creators to own their destiny  # noqa: E501

    OpenAPI spec version: 2021.11.26
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.v1_campaigns_body import V1CampaignsBody  # noqa: E501
from swagger_client.rest import ApiException


class TestV1CampaignsBody(unittest.TestCase):
    """V1CampaignsBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1CampaignsBody(self):
        """Test V1CampaignsBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.v1_campaigns_body.V1CampaignsBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
