# coding: utf-8

"""
    Klaviyo API

    Empowering creators to own their destiny  # noqa: E501

    OpenAPI spec version: 2021.11.26
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.data_privacy_api import DataPrivacyApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDataPrivacyApi(unittest.TestCase):
    """DataPrivacyApi unit test stubs"""

    def setUp(self):
        self.api = DataPrivacyApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_request_deletion(self):
        """Test case for request_deletion

        Request a Deletion  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
