# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: token_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import query_pb2 as query__pb2
import response_pb2 as response__pb2
import transaction_response_pb2 as transaction__response__pb2
import transaction_pb2 as transaction__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='token_service.proto',
  package='proto',
  syntax='proto3',
  serialized_options=b'\n&com.hederahashgraph.service.proto.java',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13token_service.proto\x12\x05proto\x1a\x0bquery.proto\x1a\x0eresponse.proto\x1a\x1atransaction_response.proto\x1a\x11transaction.proto2\xd0\t\n\x0cTokenService\x12=\n\x0b\x63reateToken\x12\x12.proto.Transaction\x1a\x1a.proto.TransactionResponse\x12=\n\x0bupdateToken\x12\x12.proto.Transaction\x1a\x1a.proto.TransactionResponse\x12;\n\tmintToken\x12\x12.proto.Transaction\x1a\x1a.proto.TransactionResponse\x12;\n\tburnToken\x12\x12.proto.Transaction\x1a\x1a.proto.TransactionResponse\x12=\n\x0b\x64\x65leteToken\x12\x12.proto.Transaction\x1a\x1a.proto.TransactionResponse\x12\x42\n\x10wipeTokenAccount\x12\x12.proto.Transaction\x1a\x1a.proto.TransactionResponse\x12\x44\n\x12\x66reezeTokenAccount\x12\x12.proto.Transaction\x1a\x1a.proto.TransactionResponse\x12\x46\n\x14unfreezeTokenAccount\x12\x12.proto.Transaction\x1a\x1a.proto.TransactionResponse\x12H\n\x16grantKycToTokenAccount\x12\x12.proto.Transaction\x1a\x1a.proto.TransactionResponse\x12K\n\x19revokeKycFromTokenAccount\x12\x12.proto.Transaction\x1a\x1a.proto.TransactionResponse\x12\x41\n\x0f\x61ssociateTokens\x12\x12.proto.Transaction\x1a\x1a.proto.TransactionResponse\x12\x42\n\x10\x64issociateTokens\x12\x12.proto.Transaction\x1a\x1a.proto.TransactionResponse\x12H\n\x16updateTokenFeeSchedule\x12\x12.proto.Transaction\x1a\x1a.proto.TransactionResponse\x12-\n\x0cgetTokenInfo\x12\x0c.proto.Query\x1a\x0f.proto.Response\x12\x38\n\x12getAccountNftInfos\x12\x0c.proto.Query\x1a\x0f.proto.Response\"\x03\x88\x02\x01\x12\x30\n\x0fgetTokenNftInfo\x12\x0c.proto.Query\x1a\x0f.proto.Response\x12\x36\n\x10getTokenNftInfos\x12\x0c.proto.Query\x1a\x0f.proto.Response\"\x03\x88\x02\x01\x12<\n\npauseToken\x12\x12.proto.Transaction\x1a\x1a.proto.TransactionResponse\x12>\n\x0cunpauseToken\x12\x12.proto.Transaction\x1a\x1a.proto.TransactionResponseB(\n&com.hederahashgraph.service.proto.javab\x06proto3'
  ,
  dependencies=[query__pb2.DESCRIPTOR,response__pb2.DESCRIPTOR,transaction__response__pb2.DESCRIPTOR,transaction__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None

_TOKENSERVICE = _descriptor.ServiceDescriptor(
  name='TokenService',
  full_name='proto.TokenService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=107,
  serialized_end=1339,
  methods=[
  _descriptor.MethodDescriptor(
    name='createToken',
    full_name='proto.TokenService.createToken',
    index=0,
    containing_service=None,
    input_type=transaction__pb2._TRANSACTION,
    output_type=transaction__response__pb2._TRANSACTIONRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='updateToken',
    full_name='proto.TokenService.updateToken',
    index=1,
    containing_service=None,
    input_type=transaction__pb2._TRANSACTION,
    output_type=transaction__response__pb2._TRANSACTIONRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='mintToken',
    full_name='proto.TokenService.mintToken',
    index=2,
    containing_service=None,
    input_type=transaction__pb2._TRANSACTION,
    output_type=transaction__response__pb2._TRANSACTIONRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='burnToken',
    full_name='proto.TokenService.burnToken',
    index=3,
    containing_service=None,
    input_type=transaction__pb2._TRANSACTION,
    output_type=transaction__response__pb2._TRANSACTIONRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='deleteToken',
    full_name='proto.TokenService.deleteToken',
    index=4,
    containing_service=None,
    input_type=transaction__pb2._TRANSACTION,
    output_type=transaction__response__pb2._TRANSACTIONRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='wipeTokenAccount',
    full_name='proto.TokenService.wipeTokenAccount',
    index=5,
    containing_service=None,
    input_type=transaction__pb2._TRANSACTION,
    output_type=transaction__response__pb2._TRANSACTIONRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='freezeTokenAccount',
    full_name='proto.TokenService.freezeTokenAccount',
    index=6,
    containing_service=None,
    input_type=transaction__pb2._TRANSACTION,
    output_type=transaction__response__pb2._TRANSACTIONRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='unfreezeTokenAccount',
    full_name='proto.TokenService.unfreezeTokenAccount',
    index=7,
    containing_service=None,
    input_type=transaction__pb2._TRANSACTION,
    output_type=transaction__response__pb2._TRANSACTIONRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='grantKycToTokenAccount',
    full_name='proto.TokenService.grantKycToTokenAccount',
    index=8,
    containing_service=None,
    input_type=transaction__pb2._TRANSACTION,
    output_type=transaction__response__pb2._TRANSACTIONRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='revokeKycFromTokenAccount',
    full_name='proto.TokenService.revokeKycFromTokenAccount',
    index=9,
    containing_service=None,
    input_type=transaction__pb2._TRANSACTION,
    output_type=transaction__response__pb2._TRANSACTIONRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='associateTokens',
    full_name='proto.TokenService.associateTokens',
    index=10,
    containing_service=None,
    input_type=transaction__pb2._TRANSACTION,
    output_type=transaction__response__pb2._TRANSACTIONRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='dissociateTokens',
    full_name='proto.TokenService.dissociateTokens',
    index=11,
    containing_service=None,
    input_type=transaction__pb2._TRANSACTION,
    output_type=transaction__response__pb2._TRANSACTIONRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='updateTokenFeeSchedule',
    full_name='proto.TokenService.updateTokenFeeSchedule',
    index=12,
    containing_service=None,
    input_type=transaction__pb2._TRANSACTION,
    output_type=transaction__response__pb2._TRANSACTIONRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='getTokenInfo',
    full_name='proto.TokenService.getTokenInfo',
    index=13,
    containing_service=None,
    input_type=query__pb2._QUERY,
    output_type=response__pb2._RESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='getAccountNftInfos',
    full_name='proto.TokenService.getAccountNftInfos',
    index=14,
    containing_service=None,
    input_type=query__pb2._QUERY,
    output_type=response__pb2._RESPONSE,
    serialized_options=b'\210\002\001',
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='getTokenNftInfo',
    full_name='proto.TokenService.getTokenNftInfo',
    index=15,
    containing_service=None,
    input_type=query__pb2._QUERY,
    output_type=response__pb2._RESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='getTokenNftInfos',
    full_name='proto.TokenService.getTokenNftInfos',
    index=16,
    containing_service=None,
    input_type=query__pb2._QUERY,
    output_type=response__pb2._RESPONSE,
    serialized_options=b'\210\002\001',
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='pauseToken',
    full_name='proto.TokenService.pauseToken',
    index=17,
    containing_service=None,
    input_type=transaction__pb2._TRANSACTION,
    output_type=transaction__response__pb2._TRANSACTIONRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='unpauseToken',
    full_name='proto.TokenService.unpauseToken',
    index=18,
    containing_service=None,
    input_type=transaction__pb2._TRANSACTION,
    output_type=transaction__response__pb2._TRANSACTIONRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_TOKENSERVICE)

DESCRIPTOR.services_by_name['TokenService'] = _TOKENSERVICE

# @@protoc_insertion_point(module_scope)
