project_name: jais
seed: 47

data:
  img: [224, 224, 3]
  normalize: True
  mean: [0.485, 0.456, 0.406]  # ImageNet mean
  std: [0.229, 0.224, 0.225]  # ImageNet std
  n_classes: None  # will define later
  classes: []  # Original ground truth names / classes

model:
  name: resnet-18
  dp: 0.2  # Dropout

loss:  # Loss settings
  smoothing: 0.1  # Label smoothing
  superloss: True
  loss_fn: CrossEntropyLoss  # Default loss function
  wts: None  # Classes weights

optm:  # Optimization settings
    name: SGD  # Name of the optimizer e.g. SGD, Adam, RMSProp, etc.
    lr: 1e-3  # Learning Rate
    wd: 1e-4  # Weight Decay
    mom: 0.9  # SGD Momentum
    nesterov: True  # SGD's Nesterov momentum
    betas: [0.90, 0.99]  # Adam's betas parameter
    amsgrad: True  # Adam's amsgrad parameter

train:
  bs: 128  # Training Batch Size
  epochs: 5
  num_workers: 4  # For PyTorch DataLoader class
  lr_range: [1e-8, 0.1]  # Learning rate (min, max) range
  wd_range: [1e-6, 1e-3]  # Weight decay (min, max) range
  mom_range: [0.85, 0.99]  # Momentum / betas (min, max) range
  mixup_alpha: 0.2

test:
  bs: 1  # Testing batch size after training

log: # logging default settings
  name: JAISLogger # Name of the logger. Name must be same as logs.conf 
  filename_prefix: jais_log
  training_log_filename_prefix: training_log
  # Number of recent log files to keep. Rest will be deleted from `logs_dir`
  keep_n_recent_logs: 5

paths:  #* FULL PATHS TO FOLDERS AND FILES
  home_dir: &home_dir !homedir  # User home folder path. e.g. `/home/<username>/` in linux
  # cache_dir: &cache_dir !joinpath [*home_dir, .jais]
  root_dir: &root_dir !rootdir # JAIS package path
  cwd: &cwd !cwd  # Current Working Directory
  
  logs_dir: !joinpath [*cwd, logs]
  data_dir: !joinpath [*cwd, data]
  chkpts_dir: !joinpath [*cwd, checkpoints]
  