
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-12-09T16:35:06-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "646e94ff806c0c133926fbb95d746fbf6325cbf3",
 "version": "1.3.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
