[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "unicodedata-reader"
version = "0.1.7"
description = ""
authors = ["Koji Ishii <kojii@chromium.org>"]
readme = "README.md"
repository = "https://github.com/kojiishi/unicodedata-reader"
license = "Apache-2.0"

[tool.poetry.dependencies]
python = ">=3.8"
platformdirs = "^2.2.0"

[tool.poetry.dev-dependencies]
pytest = "*"
pytype = {version = "*", python = "<3.10"}
tox = "^3.24.4"
yapf = "^0.31.0"

[tool.poetry.scripts]
unicodedata-reader = 'unicodedata_reader.__main__:main'

[tool.pytest.ini_options]
testpaths = "tests"

[tool.yapf]
based_on_style = "pep8"
