
[tool.poetry]
name = "ani-cli"
version = "0.1.0"
description = ""
authors = ["sleepntsheep <sheep@papangkorn.com>"]
packages = [
    { include = "ani-cli" },
    { include = "ani-cli/**/*.py" },
]

[tool.poetry.dependencies]
python = "^3.7"
InquirerPy = "^0.3.0"
requests = "^2.26.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
ani = 'main:main'