[tool.poetry]
name = "puc_lpgomes_csvconverter"
version = "0.1.3"
description = "Convert CSV to Json. For only purpose at PUC Python Class"
authors = ["Leandro P. Gomes <leandropgomes11@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
pandas = "^1.3.4"
click = "^8.0.3"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
flake8 = "^4.0.1"
mypy = "^0.910"
black = "^21.11b1"
pandas-stubs = "^1.2.0"
ipython = "^7.30.1"
isort = "^5.10.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
csv_converter = 'puc_lpgomes_csvconverter.converter:converter'

[tool.black]
line-length = 99

[tool.isort]
profile = "black"
