name: CI

on:
  pull_request:
    branches:
      - master
  release:
    types: [created]
  push:
    branches:
      - master
  schedule:
    - cron: "20 23 * * 4"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install GDAL
        run: |
          sudo apt-get update
          sudo apt-get install cmake libgdal-dev

      - name: Install latest stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - name: Lint with rustfmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt

      - name: Lint with clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-targets --all-features

      # using a venv to make `maturin develop` work
      - name: create a virtualenv and install Python dependencies
        run: |
          python -m venv venv
          . venv/bin/activate
          python install-dev-dependencies.py

      - name: Build python extension with maturin
        run: |
          . venv/bin/activate
          maturin develop

      - name: pytest
        run: |
          . venv/bin/activate
          pytest -v

#  build:
#    if: ${{ false }}  # disable for now
#    runs-on: ${{ matrix.os }}
#    needs: lint
#    strategy:
#      fail-fast: false
#      matrix:
#        python-version: [3.8]
#        os: [
#            ubuntu-latest,
#            #macos-latest,
#            windows-latest
#        ]
#
#    steps:
#
#      # https://github.com/rust-lang/rust-bindgen/issues/1797#issuecomment-787503355
#      - name: Install LLVM and Clang # required for bindgen to work, see https://github.com/rust-lang/rust-bindgen/issues/1797
#        uses: KyleMayes/install-llvm-action@32c4866ebb71e0949e8833eb49beeebed48532bd
#        if: matrix.os == 'windows-latest'
#        with:
#          version: "11.0"
#          directory: ${{ runner.temp }}/llvm
#
#      - name: Set LIBCLANG_PATH
#        run: echo "LIBCLANG_PATH=$((gcm clang).source -replace "clang.exe")" >> $env:GITHUB_ENV
#        if: matrix.os == 'windows-latest'
#
#      - name: Checkout
#        uses: actions/checkout@v1
#
#      - name: Pull git submodules
#        run: |
#          git submodule init
#          git submodule update
#
#      - name: Set up Python ${{ matrix.python-version }}
#        uses: actions/setup-python@v1
#        with:
#          python-version: ${{ matrix.python-version }}
#
#      - name: Install latest stable
#        uses: actions-rs/toolchain@v1
#        with:
#          toolchain: stable
#          override: true
#
#      - name: Install Python dependencies
#        working-directory: h3ronpy
#        run: python install-dev-dependencies.py
#
#      - name: Build with cargo
#        uses: actions-rs/cargo@v1.0.1
#        with:
#          command: build
#          toolchain: stable
#
#      - name: Build python extension with maturin
#        working-directory: h3ronpy
#        run: maturin build

  python-publish-manylinux-2-24:
    if: (github.event_name == 'release' && github.event.action == 'created') || github.event_name == 'schedule'
    needs: lint
    runs-on: ubuntu-latest
    container: quay.io/pypa/manylinux_2_24_x86_64
    steps:

      - uses: actions/checkout@v1

      - name: Install latest stable rust
        run: |
          curl --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- --profile minimal --default-toolchain stable -y

      - name: Install dependencies
        run: |
          apt update
          apt install -y libgdal-dev clang-7
          export PATH="/opt/python/cp38-cp38/bin/:$PATH"
          pip install wheel
          python install-dev-dependencies.py

      - name: Build Python package
        shell: bash
        run: |
          source $HOME/.cargo/env
          export PATH="/opt/python/cp38-cp38/bin/:$PATH"
          maturin build --release --strip --interpreter /opt/python/cp38-cp38/bin/python --manylinux 2_24

      - name: List wheels
        run: find ./target/wheels/

      - name: Install wheels
        run: |
          export PATH="/opt/python/cp38-cp38/bin/:$PATH"
          pip install target/wheels/h3ronpy*.whl

      - name: PyPi publish
        if: github.event_name == 'release' && github.event.action == 'created'
        env:
          MATURIN_PASSWORD: ${{ secrets.PYPI }}
        shell: bash
        run: |
          source $HOME/.cargo/env
          export PATH="/opt/python/cp38-cp38/bin/:$PATH"
          maturin publish --username __token__

