
stages:
  - build
  - release

workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS'
      when: never
    - if: '$CI_COMMIT_BRANCH'
    - if: '$CI_COMMIT_TAG'


build:
  stage: build
  image: python:latest
  script:
    - pip install flit
    - flit build
  artifacts:
    paths:
    - dist/*.whl

release:
  stage: release
  image: python:latest
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - pip install flit
    - pip install twine
    - flit build
    - TWINE_PASSWORD=${CI_JOB_TOKEN} TWINE_USERNAME=gitlab-ci-token python -m twine upload --repository-url ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi dist/*

