[tool.poetry]
name = "dj-datatables-view"
version = "0.1.0"
description = "Django datatables view fork from django-datatables-view"
authors = ["Longbowou <blandedaniel@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
Django = "^4.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
