[tool.poetry]
name = "posit-playground"
version = "0.1.0"
description = "Posit arithmetic library with no frills"
authors = ["Francesco Urbani <francescourbanidue@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
softposit = "^0.3.4.4"
pytest = "^6.2.5"
numpy = "^1.21.4"


[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 119
target-version = ['py39']
include = '\.pyi?$'
