# coding: utf-8

"""
    Napoleon S&L API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.2.130
    Contact: ag@napoleonit.ru
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class CartItems(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'gifts': 'list[CartItem]',
        'goods': 'list[CartItemWithExtra]'
    }

    attribute_map = {
        'gifts': 'gifts',
        'goods': 'goods'
    }

    def __init__(self, gifts=None, goods=None):  # noqa: E501
        """CartItems - a model defined in Swagger"""  # noqa: E501

        self._gifts = None
        self._goods = None
        self.discriminator = None

        if gifts is not None:
            self.gifts = gifts
        if goods is not None:
            self.goods = goods

    @property
    def gifts(self):
        """Gets the gifts of this CartItems.  # noqa: E501

        Подарки  # noqa: E501

        :return: The gifts of this CartItems.  # noqa: E501
        :rtype: list[CartItem]
        """
        return self._gifts

    @gifts.setter
    def gifts(self, gifts):
        """Sets the gifts of this CartItems.

        Подарки  # noqa: E501

        :param gifts: The gifts of this CartItems.  # noqa: E501
        :type: list[CartItem]
        """

        self._gifts = gifts

    @property
    def goods(self):
        """Gets the goods of this CartItems.  # noqa: E501

        Товары в корзине  # noqa: E501

        :return: The goods of this CartItems.  # noqa: E501
        :rtype: list[CartItemWithExtra]
        """
        return self._goods

    @goods.setter
    def goods(self, goods):
        """Sets the goods of this CartItems.

        Товары в корзине  # noqa: E501

        :param goods: The goods of this CartItems.  # noqa: E501
        :type: list[CartItemWithExtra]
        """

        self._goods = goods

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CartItems, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CartItems):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
