# coding: utf-8

"""
    Napoleon S&L API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.2.130
    Contact: ag@napoleonit.ru
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class CartItemData(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'description': 'str',
        'image': 'str',
        'name': 'str',
        'remote_id': 'str'
    }

    attribute_map = {
        'description': 'description',
        'image': 'image',
        'name': 'name',
        'remote_id': 'remoteId'
    }

    def __init__(self, description=None, image=None, name=None, remote_id=None):  # noqa: E501
        """CartItemData - a model defined in Swagger"""  # noqa: E501

        self._description = None
        self._image = None
        self._name = None
        self._remote_id = None
        self.discriminator = None

        if description is not None:
            self.description = description
        if image is not None:
            self.image = image
        if name is not None:
            self.name = name
        if remote_id is not None:
            self.remote_id = remote_id

    @property
    def description(self):
        """Gets the description of this CartItemData.  # noqa: E501

        Описание товара  # noqa: E501

        :return: The description of this CartItemData.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this CartItemData.

        Описание товара  # noqa: E501

        :param description: The description of this CartItemData.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def image(self):
        """Gets the image of this CartItemData.  # noqa: E501

        Ссылка на изображение  # noqa: E501

        :return: The image of this CartItemData.  # noqa: E501
        :rtype: str
        """
        return self._image

    @image.setter
    def image(self, image):
        """Sets the image of this CartItemData.

        Ссылка на изображение  # noqa: E501

        :param image: The image of this CartItemData.  # noqa: E501
        :type: str
        """

        self._image = image

    @property
    def name(self):
        """Gets the name of this CartItemData.  # noqa: E501

        Название  # noqa: E501

        :return: The name of this CartItemData.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this CartItemData.

        Название  # noqa: E501

        :param name: The name of this CartItemData.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def remote_id(self):
        """Gets the remote_id of this CartItemData.  # noqa: E501

        Идентификатор в сторонней системе  # noqa: E501

        :return: The remote_id of this CartItemData.  # noqa: E501
        :rtype: str
        """
        return self._remote_id

    @remote_id.setter
    def remote_id(self, remote_id):
        """Sets the remote_id of this CartItemData.

        Идентификатор в сторонней системе  # noqa: E501

        :param remote_id: The remote_id of this CartItemData.  # noqa: E501
        :type: str
        """

        self._remote_id = remote_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CartItemData, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CartItemData):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
