# coding: utf-8

"""
    Napoleon S&L API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.2.130
    Contact: ag@napoleonit.ru
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class Promocode(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'amount': 'int',
        'cid': 'str',
        'code': 'str',
        'codes': 'list[str]',
        'created_at': 'int',
        'id': 'str',
        'items': 'list[PromocodeItem]',
        'push_text': 'str',
        'shop_id': 'str',
        'start_at': 'str',
        'updated_at': 'int'
    }

    attribute_map = {
        'amount': 'amount',
        'cid': 'cid',
        'code': 'code',
        'codes': 'codes',
        'created_at': 'created_at',
        'id': 'id',
        'items': 'items',
        'push_text': 'push_text',
        'shop_id': 'shopId',
        'start_at': 'start_at',
        'updated_at': 'updated_at'
    }

    def __init__(self, amount=None, cid=None, code=None, codes=None, created_at=None, id=None, items=None, push_text=None, shop_id=None, start_at=None, updated_at=None):  # noqa: E501
        """Promocode - a model defined in Swagger"""  # noqa: E501

        self._amount = None
        self._cid = None
        self._code = None
        self._codes = None
        self._created_at = None
        self._id = None
        self._items = None
        self._push_text = None
        self._shop_id = None
        self._start_at = None
        self._updated_at = None
        self.discriminator = None

        if amount is not None:
            self.amount = amount
        if cid is not None:
            self.cid = cid
        if code is not None:
            self.code = code
        self.codes = codes
        if created_at is not None:
            self.created_at = created_at
        if id is not None:
            self.id = id
        if items is not None:
            self.items = items
        self.push_text = push_text
        if shop_id is not None:
            self.shop_id = shop_id
        self.start_at = start_at
        if updated_at is not None:
            self.updated_at = updated_at

    @property
    def amount(self):
        """Gets the amount of this Promocode.  # noqa: E501

        (read-only) Количество промокодов  # noqa: E501

        :return: The amount of this Promocode.  # noqa: E501
        :rtype: int
        """
        return self._amount

    @amount.setter
    def amount(self, amount):
        """Sets the amount of this Promocode.

        (read-only) Количество промокодов  # noqa: E501

        :param amount: The amount of this Promocode.  # noqa: E501
        :type: int
        """

        self._amount = amount

    @property
    def cid(self):
        """Gets the cid of this Promocode.  # noqa: E501

        (read-only) ID компании  # noqa: E501

        :return: The cid of this Promocode.  # noqa: E501
        :rtype: str
        """
        return self._cid

    @cid.setter
    def cid(self, cid):
        """Sets the cid of this Promocode.

        (read-only) ID компании  # noqa: E501

        :param cid: The cid of this Promocode.  # noqa: E501
        :type: str
        """

        self._cid = cid

    @property
    def code(self):
        """Gets the code of this Promocode.  # noqa: E501

        Промокод  # noqa: E501

        :return: The code of this Promocode.  # noqa: E501
        :rtype: str
        """
        return self._code

    @code.setter
    def code(self, code):
        """Sets the code of this Promocode.

        Промокод  # noqa: E501

        :param code: The code of this Promocode.  # noqa: E501
        :type: str
        """

        self._code = code

    @property
    def codes(self):
        """Gets the codes of this Promocode.  # noqa: E501

        Список промокодов  # noqa: E501

        :return: The codes of this Promocode.  # noqa: E501
        :rtype: list[str]
        """
        return self._codes

    @codes.setter
    def codes(self, codes):
        """Sets the codes of this Promocode.

        Список промокодов  # noqa: E501

        :param codes: The codes of this Promocode.  # noqa: E501
        :type: list[str]
        """
        if codes is None:
            raise ValueError("Invalid value for `codes`, must not be `None`")  # noqa: E501

        self._codes = codes

    @property
    def created_at(self):
        """Gets the created_at of this Promocode.  # noqa: E501

        (read-only) Время создания записи  # noqa: E501

        :return: The created_at of this Promocode.  # noqa: E501
        :rtype: int
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """Sets the created_at of this Promocode.

        (read-only) Время создания записи  # noqa: E501

        :param created_at: The created_at of this Promocode.  # noqa: E501
        :type: int
        """

        self._created_at = created_at

    @property
    def id(self):
        """Gets the id of this Promocode.  # noqa: E501

        (read-only) ID акции  # noqa: E501

        :return: The id of this Promocode.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Promocode.

        (read-only) ID акции  # noqa: E501

        :param id: The id of this Promocode.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def items(self):
        """Gets the items of this Promocode.  # noqa: E501

        Список товаров  # noqa: E501

        :return: The items of this Promocode.  # noqa: E501
        :rtype: list[PromocodeItem]
        """
        return self._items

    @items.setter
    def items(self, items):
        """Sets the items of this Promocode.

        Список товаров  # noqa: E501

        :param items: The items of this Promocode.  # noqa: E501
        :type: list[PromocodeItem]
        """

        self._items = items

    @property
    def push_text(self):
        """Gets the push_text of this Promocode.  # noqa: E501

        Текст Push-сообщений  # noqa: E501

        :return: The push_text of this Promocode.  # noqa: E501
        :rtype: str
        """
        return self._push_text

    @push_text.setter
    def push_text(self, push_text):
        """Sets the push_text of this Promocode.

        Текст Push-сообщений  # noqa: E501

        :param push_text: The push_text of this Promocode.  # noqa: E501
        :type: str
        """
        if push_text is None:
            raise ValueError("Invalid value for `push_text`, must not be `None`")  # noqa: E501

        self._push_text = push_text

    @property
    def shop_id(self):
        """Gets the shop_id of this Promocode.  # noqa: E501

        Идентификатор  # noqa: E501

        :return: The shop_id of this Promocode.  # noqa: E501
        :rtype: str
        """
        return self._shop_id

    @shop_id.setter
    def shop_id(self, shop_id):
        """Sets the shop_id of this Promocode.

        Идентификатор  # noqa: E501

        :param shop_id: The shop_id of this Promocode.  # noqa: E501
        :type: str
        """

        self._shop_id = shop_id

    @property
    def start_at(self):
        """Gets the start_at of this Promocode.  # noqa: E501

        Время начала акции (ISO8601 / RFC3339)  # noqa: E501

        :return: The start_at of this Promocode.  # noqa: E501
        :rtype: str
        """
        return self._start_at

    @start_at.setter
    def start_at(self, start_at):
        """Sets the start_at of this Promocode.

        Время начала акции (ISO8601 / RFC3339)  # noqa: E501

        :param start_at: The start_at of this Promocode.  # noqa: E501
        :type: str
        """
        if start_at is None:
            raise ValueError("Invalid value for `start_at`, must not be `None`")  # noqa: E501

        self._start_at = start_at

    @property
    def updated_at(self):
        """Gets the updated_at of this Promocode.  # noqa: E501

        (read-only) Время обновления записи  # noqa: E501

        :return: The updated_at of this Promocode.  # noqa: E501
        :rtype: int
        """
        return self._updated_at

    @updated_at.setter
    def updated_at(self, updated_at):
        """Sets the updated_at of this Promocode.

        (read-only) Время обновления записи  # noqa: E501

        :param updated_at: The updated_at of this Promocode.  # noqa: E501
        :type: int
        """

        self._updated_at = updated_at

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Promocode, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Promocode):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
