# coding: utf-8

"""
    Napoleon S&L API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.2.130
    Contact: ag@napoleonit.ru
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class TalanConfirmationQuery(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'app_type': 'str',
        'code': 'str',
        'type': 'str',
        'value': 'str'
    }

    attribute_map = {
        'app_type': 'appType',
        'code': 'code',
        'type': 'type',
        'value': 'value'
    }

    def __init__(self, app_type=None, code=None, type=None, value=None):  # noqa: E501
        """TalanConfirmationQuery - a model defined in Swagger"""  # noqa: E501

        self._app_type = None
        self._code = None
        self._type = None
        self._value = None
        self.discriminator = None

        self.app_type = app_type
        self.code = code
        self.type = type
        self.value = value

    @property
    def app_type(self):
        """Gets the app_type of this TalanConfirmationQuery.  # noqa: E501


        :return: The app_type of this TalanConfirmationQuery.  # noqa: E501
        :rtype: str
        """
        return self._app_type

    @app_type.setter
    def app_type(self, app_type):
        """Sets the app_type of this TalanConfirmationQuery.


        :param app_type: The app_type of this TalanConfirmationQuery.  # noqa: E501
        :type: str
        """
        if app_type is None:
            raise ValueError("Invalid value for `app_type`, must not be `None`")  # noqa: E501

        self._app_type = app_type

    @property
    def code(self):
        """Gets the code of this TalanConfirmationQuery.  # noqa: E501


        :return: The code of this TalanConfirmationQuery.  # noqa: E501
        :rtype: str
        """
        return self._code

    @code.setter
    def code(self, code):
        """Sets the code of this TalanConfirmationQuery.


        :param code: The code of this TalanConfirmationQuery.  # noqa: E501
        :type: str
        """
        if code is None:
            raise ValueError("Invalid value for `code`, must not be `None`")  # noqa: E501

        self._code = code

    @property
    def type(self):
        """Gets the type of this TalanConfirmationQuery.  # noqa: E501

        Тип value: phone, email   * email - \"(^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\\.[a-zA-Z0-9-.]+$)\"   * phone - \"^[0-9]{11,13}$\" (только числа от 11 до 13 символов)   # noqa: E501

        :return: The type of this TalanConfirmationQuery.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this TalanConfirmationQuery.

        Тип value: phone, email   * email - \"(^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\\.[a-zA-Z0-9-.]+$)\"   * phone - \"^[0-9]{11,13}$\" (только числа от 11 до 13 символов)   # noqa: E501

        :param type: The type of this TalanConfirmationQuery.  # noqa: E501
        :type: str
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501
        allowed_values = ["phone", "email"]  # noqa: E501
        if type not in allowed_values:
            raise ValueError(
                "Invalid value for `type` ({0}), must be one of {1}"  # noqa: E501
                .format(type, allowed_values)
            )

        self._type = type

    @property
    def value(self):
        """Gets the value of this TalanConfirmationQuery.  # noqa: E501

        email or phone  # noqa: E501

        :return: The value of this TalanConfirmationQuery.  # noqa: E501
        :rtype: str
        """
        return self._value

    @value.setter
    def value(self, value):
        """Sets the value of this TalanConfirmationQuery.

        email or phone  # noqa: E501

        :param value: The value of this TalanConfirmationQuery.  # noqa: E501
        :type: str
        """
        if value is None:
            raise ValueError("Invalid value for `value`, must not be `None`")  # noqa: E501

        self._value = value

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TalanConfirmationQuery, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TalanConfirmationQuery):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
