queue_rules:
  - name: default
    conditions:
      - base=main
      - check-success=build-deploy-docs
      - check-success=lint
      - check-success=dev-deps (macos-10.15, 3.6)
      - check-success=dev-deps (macos-10.15, 3.10)
      - check-success=dev-deps (ubuntu-18.04, 3.6)
      - check-success=dev-deps (ubuntu-18.04, 3.10)
      - check-success=dev-deps (windows-2019, 3.6)
      - check-success=dev-deps (windows-2019, 3.10)
      - check-success=tests (macos-10.15, 3.6)
      - check-success=tests (macos-10.15, 3.10)
      - check-success=tests (ubuntu-18.04, 3.6)
      - check-success=tests (ubuntu-18.04, 3.10)
      - check-success=tests (windows-2019, 3.6)
      - check-success=tests (windows-2019, 3.10)

pull_request_rules:
  - name: automatic merge for Dependabot pull requests
    conditions:
      - base=main
      - author~=^dependabot(|-preview)\[bot\]$
      - label=dependencies
      - check-success=build-deploy-docs
      - check-success=lint
      - check-success=dev-deps (macos-10.15, 3.6)
      - check-success=dev-deps (macos-10.15, 3.10)
      - check-success=dev-deps (ubuntu-18.04, 3.6)
      - check-success=dev-deps (ubuntu-18.04, 3.10)
      - check-success=dev-deps (windows-2019, 3.6)
      - check-success=dev-deps (windows-2019, 3.10)
      - check-success=tests (macos-10.15, 3.6)
      - check-success=tests (macos-10.15, 3.10)
      - check-success=tests (ubuntu-18.04, 3.6)
      - check-success=tests (ubuntu-18.04, 3.10)
      - check-success=tests (windows-2019, 3.6)
      - check-success=tests (windows-2019, 3.10)
    actions:
      queue:
        name: default
