"""
Autogenerated state module using `pop-create-idem <https://gitlab.com/saltstack/pop/pop-create-idem>`__

hub.exec.boto3.client.ec2.create_local_gateway_route
hub.exec.boto3.client.ec2.delete_local_gateway_route
hub.exec.boto3.client.ec2.search_local_gateway_routes
"""



import copy
from typing import *
import dict_tools.differ as differ

async def present(hub, ctx, name: Text, destination_cidr_block: Text, local_gateway_route_table_id: Text, local_gateway_virtual_interface_group_id: Text)  -> Dict[str, Any]:
    r'''
    **Autogenerated function**
    
    Creates a static route for the specified local gateway route table.

    Args:
        name(Text): A name, ID, or JMES search path to identify the resource.
        destination_cidr_block(Text): The CIDR range used for destination matches. Routing decisions are based on the most specific
            match.
        local_gateway_route_table_id(Text): The ID of the local gateway route table.
        local_gateway_virtual_interface_group_id(Text): The ID of the virtual interface group.

    Returns:
        Dict[str, Any]

    Examples:

        .. code-block:: sls

            resource_is_present:
              aws_auto.ec2.local_gateway_route.present:
                - name: value
                - destination_cidr_block: value
                - local_gateway_route_table_id: value
                - local_gateway_virtual_interface_group_id: value
    '''

    
    result = dict(comment="", changes= None, name=name, result=True)
    ret = await hub.exec.boto3.client.ec2.local_gateway_route.id(
        ctx,
        jmes_path=name
    )
    if ret["status"]:
        # name is now the first id that matched the JMES search path
        name = ret["ret"]
    

    
    before = await hub.exec.boto3.client.ec2.search_local_gateway_routes(name)

    if before:
        result["comment"] = f"'{name}' already exists"
    else:
        try:
            ret = await hub.exec.boto3.client.ec2.create_local_gateway_route(
                ctx,
                DryRun=ctx.test,
                
                **{"DestinationCidrBlock": destination_cidr_block, "LocalGatewayRouteTableId": local_gateway_route_table_id, "LocalGatewayVirtualInterfaceGroupId": local_gateway_virtual_interface_group_id}
            )
            result["result"] = ret["status"]
            if not result["result"]:
                result["comment"] = ret["comment"]
                return result
            ret["comment"] = f"Created '{name}'"
        except hub.tool.boto3.exception.ClientError as e:
            result["comment"] = f"{e.__class__.__name__}: {e}"

    
    # TODO perform other modifications as needed here
    ...

    after = await hub.exec.boto3.client.ec2.search_local_gateway_routes(name)
    result["changes"] = differ.deep_diff(before, after)
    return result



async def absent(hub, ctx, name: Text, destination_cidr_block: Text, local_gateway_route_table_id: Text)  -> Dict[str, Any]:
    r'''
    **Autogenerated function**
    
    Deletes the specified route from the specified local gateway route table.

    Args:
        name(Text): A name, ID, or JMES search path to identify the resource.
        destination_cidr_block(Text): The CIDR range for the route. This must match the CIDR for the route exactly.
        local_gateway_route_table_id(Text): The ID of the local gateway route table.

    Returns:
        Dict[str, Any]

    Examples:

        .. code-block:: sls

            resource_is_absent:
              aws_auto.ec2.local_gateway_route.absent:
                - name: value
                - destination_cidr_block: value
                - local_gateway_route_table_id: value
    '''

    
    result = dict(comment="", changes= None, name=name, result=True)
    ret = await hub.exec.boto3.client.ec2.local_gateway_route.id(
        ctx,
        jmes_path=name
    )
    if ret["status"]:
        # name is now the first id that matched the JMES search path
        name = ret["ret"]
    

    

    before = await hub.exec.boto3.client.ec2.search_local_gateway_routes(name)

    if not before:
        result["comment"] = f"'{name}' already absent"
    else:
        try:
            ret = await hub.exec.boto3.client.ec2.delete_local_gateway_route(
                ctx,
                DryRun=ctx.test,
                
                **{"DestinationCidrBlock": destination_cidr_block, "LocalGatewayRouteTableId": local_gateway_route_table_id}
            )
            result["result"] = ret["status"]
            if not result["result"]:
                result["comment"] = ret["comment"]
                return result
            result["comment"] = f"Deleted '{name}'"
        except hub.tool.boto3.exception.ClientError as e:
            result["comment"] = f"{e.__class__.__name__}: {e}"

    

    after = await hub.exec.boto3.client.ec2.search_local_gateway_routes(name)
    result["changes"] = differ.deep_diff(before, after)
    return result



async def describe(hub, ctx)  -> Dict[str, Dict[str, Any]]:
    r'''
    **Autogenerated function**

    Describe the resource in a way that can be recreated/managed with the corresponding "present" function

    
    Searches for routes in the specified local gateway route table.


    Returns:
        Dict[str, Any]

    Examples:

        .. code-block:: bash

            $ idem describe aws_auto.ec2.local_gateway_route
    '''

    
    result = {}

    ret = await hub.exec.boto3.client.ec2.search_local_gateway_routes(ctx)
    if not ret["status"]:
        hub.log.debug(f"Could not describe local_gateway_route {ret['comment']}")
        return result

    for local_gateway_route in ret["ret"]["TODO"]:
        new_local_gateway_route = [
                {"LocalGatewayRouteTableId": local_gateway_route_table_id, "Filters": filters, "MaxResults": max_results, "NextToken": next_token}
        ]
        result[local_gateway_route["local_gateway_routeId"]] = {"aws_auto.ec2.local_gateway_route.present": new_local_gateway_route}

        for i, data in enumerate(local_gateway_route.get("", ())):
            sub_local_gateway_route = copy.deepcopy(new_local_gateway_route)

            # TODO check for subresouruces
            sub_local_gateway_route.append({})
            sub_local_gateway_route.append({"name": "TODOs"})
            result[f"TODOs-{i}"] = {"aws_auto.ec2.local_gateway_route.present": sub_local_gateway_route}

    return result


