# coding: utf-8

"""
    Napoleon S&L API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.2.130
    Contact: ag@napoleonit.ru
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import sl_api_client
from sl_api_client.models.order_v2_user_payment import OrderV2UserPayment  # noqa: E501
from sl_api_client.rest import ApiException


class TestOrderV2UserPayment(unittest.TestCase):
    """OrderV2UserPayment unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOrderV2UserPayment(self):
        """Test OrderV2UserPayment"""
        # FIXME: construct object with mandatory attributes with example values
        # model = sl_api_client.models.order_v2_user_payment.OrderV2UserPayment()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
