# coding: utf-8

"""
    Napoleon S&L API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.2.130
    Contact: ag@napoleonit.ru
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import sl_api_client
from sl_api_client.models.card_activation import CardActivation  # noqa: E501
from sl_api_client.rest import ApiException


class TestCardActivation(unittest.TestCase):
    """CardActivation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCardActivation(self):
        """Test CardActivation"""
        # FIXME: construct object with mandatory attributes with example values
        # model = sl_api_client.models.card_activation.CardActivation()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
