# coding: utf-8

"""
    Napoleon S&L API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.2.130
    Contact: ag@napoleonit.ru
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import sl_api_client
from sl_api_client.api.talan_auth_api import TalanAuthApi  # noqa: E501
from sl_api_client.rest import ApiException


class TestTalanAuthApi(unittest.TestCase):
    """TalanAuthApi unit test stubs"""

    def setUp(self):
        self.api = sl_api_client.api.talan_auth_api.TalanAuthApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_post_talan_auth_signin_code(self):
        """Test case for post_talan_auth_signin_code

        Запросить код авторизации  # noqa: E501
        """
        pass

    def test_post_talan_auth_signin_code_confirmation(self):
        """Test case for post_talan_auth_signin_code_confirmation

        Подтверждение кода авторизации  # noqa: E501
        """
        pass

    def test_post_talan_auth_token_refresh(self):
        """Test case for post_talan_auth_token_refresh

        Получение нового токена  # noqa: E501
        """
        pass

    def test_post_talan_auth_verify_communication(self):
        """Test case for post_talan_auth_verify_communication

        Подтверждение средства связи  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
