start:
  - title: Startifact organisation setup
  - text:
      Please refer to the documentation at
      https://cariad.github.io/startifact for guidance.
  - text:
      You organisation's configuration will be created as a Systems Manager
      parameter named {param_fmt} in {region_fmt} of account {account_fmt}.
  - ask:
      question: Is this okay?
      key: start_ok
      branches:
        - response: y
          then:
            - goto: bucket_param_name
        - response: n
          then:
            - stop: false

bucket_param_name:
  - text:
      Enter the name of the Systems Manager parameter that holds the name of
      your artifacts bucket.
  - text:
      This parameter must exist already.
  - ask:
      question: Bucket parameter?
      key: bucket_param_name
      recall: true
      branches:
        - response: "^.+$"
          then:
            - goto: bucket_param_region

bucket_param_region:
  - ask:
      question: Bucket name parameter region?
      key: bucket_param_region
      recall: true
      branches:
        - response: "^.+$"
          then:
            - goto: bucket_region

bucket_region:
  - ask:
      question: Bucket region?
      key: bucket_region
      recall: true
      branches:
        - response: "^.+$"
          then:
            - goto: bucket_key_prefix

bucket_key_prefix:
  - text:
      A key prefix isn't necessary if Startifact is the only tool that will read
      and write from the artifacts bucket.
  - text:
      If the bucket needs to be shared with other processes then a unique key
      prefix can prevent Startifact clobbering and being clobbered.
  - ask:
      question: Bucket key prefix?
      key: bucket_key_prefix
      recall: true
      branches:
        - response: "^.*$"
          then:
            - goto: parameter_region

parameter_region:
  - text:
      Startifact records the latest version of each artifact as Systems Manager
      parameters.
  - text: These parameters can be created in any region.
  - ask:
      question: Artifact parameter region?
      key: parameter_region
      recall: true
      branches:
        - response: "^.+$"
          then:
            - goto: parameter_name_prefix

parameter_name_prefix:
  - text:
      By default, the latest version of each artifact will be recorded in
      Systems Manager as /NAME/Latest.
  - text:
      Any name prefix you specify will be prepended to this name. For example,
      the prefix "/org" will create parameters named "/org/NAME/Latest".
  - ask:
      question: Artifact parameter name prefix?
      key: parameter_name_prefix
      recall: true
      branches:
        - response: "^.*$"
          then:
            - goto: finalise

finalise:
  - text:
      Ready to save your configuration to the {param_fmt} Systems Manager parameter in
      region {region_fmt} in account {account_fmt}.
  - responses: json
  - ask:
      question: Okay to save?
      key: save_ok
      branches:
        - response: y
          then:
            - stop: true
        - response: n
          then:
            - stop: false
