name: Release

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
        fetch-depth: 0
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 install -U setuptools wheel twine
        pip3 install ".[all]"
    - name: Make sure unit tests succeed
      run: |
        pytest
    - name: Build package & publish to PyPi
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        python3 setup.py sdist bdist_wheel
        twine upload dist/*
    - name: Deploy mkdocs site
      run: | 
        mkdocs gh-deploy --force
