[tool.poetry]
name = "mgwrvisualizer"
version = "0.0.3"
description = "Visualization Suite for Multiscale Geographically Weighted Regression (MGWR) "
authors = ["Matthew Tralka <matthew@tralka.xyz>"]
include = ["webclient_dist/**/*"]
license = "MIT"
repository = "https://github.com/mtralka/MGWRVisualizer"
readme = "README.md"
keywords = [
    "multiscale geographic weighted regression", 
    "MGWR", "spatial statistics", "education",
    "visualization"
    ]

classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Science/Research",
    "Intended Audience :: Education",
    "Intended Audience :: Developers",
    "Topic :: Scientific/Engineering",
    "Topic :: Scientific/Engineering :: GIS",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.7",
]


[tool.poetry.dependencies]
python = ">=3.7.1,<3.11"
pandas = "^1.3.4"
numpy = "^1.21.4"

[tool.poetry.dev-dependencies]
black = "^21.11b1"
mypy = "^0.910"
notebook = "^6.4.6"
pre-commit = "^2.16.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
