[tool.poetry]
name = "Csaad_Crypto2"
version = "0.1.0"
description = ""
authors = ["Carlos Saad <csaad@alumni.unav.es>"]

[tool.poetry.dependencies]
python = "^3.8"
pandas = "^1.3.4"
krakenex = "^2.1.0"
dash = "^2.0.0"
plotly = "^5.4.0"
pykrakenapi = "^0.2.3"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
