
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-12-09T21:18:06-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "17e680512fce6c27629c2ef1e546414ae823c79e",
 "version": "0.8.16b0.dev202112100713"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
