#[tool.poetry]
#name = "volttron-utils"
#version = "0.3.2"
#description = "Utility classes and methods for VOLTTRON"
#authors = ["C. Allwardt <craig.allwardt@pnnl.gov>"]
#license = "Apache-2.0"
#packages = [
#    { include = "volttron" }
#]
#homepage = "https://github.com/VOLTTRON/volttron-utils"
#repository = "https://github.com/VOLTTRON/volttron-utils"
#
#keywords = ["volttron"]
#
#[tool.poetry.dependencies]
#python = ">=3.6.2,<4.0"
#gevent = "20.6.1"
#greenlet = "0.4.16"
#watchdog-gevent = "^0.1.1"
#zmq = "^0.0.0"
#dateutils = "^0.6.7"
#tzlocal = "2.1"
#cryptography = "2.3"
#pyOpenSSL = "19.0.0"
#psutil = "^5.7.0"
#PyYAML = "^5.4.1"
#
#[tool.poetry.dev-dependencies]
#pytest = "^6.2.4"
#black = "^21.6b0"
#flake8 = "^3.9.2"
#pre-commit = "^2.14.1"
#
#[build-system]
#requires = ["poetry-core>=1.0.0"]
#build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 79
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/'''
