on: [ push, pull_request ]
name: mypy type checking
jobs:
    mypy:
        runs-on: ubuntu-latest
        container:
            image: archlinux:latest
        steps:
            - uses: actions/checkout@v2
            - run: pacman --noconfirm -Syu python mypy python-pip
            - run: python -m pip install --upgrade pip
            - run: pip install fastapi pydantic
            - run: export MYPYPATH=ourkvm/
            - name: run mypy
              run: mypy --strict --module ourkvm