[tool.poetry]
name = "errui"
version = "0.1.0"
description = "Error handling for end users"
readme = "README.md"
authors = ["Maximillian Strand <maximillian.strand@protonmail.com>"]
repository = "https://gitlab.com/deepadmax/errui"

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
