# Package Overview
package_name: classification_model

# Data Files
training_data_file: train.csv
test_data_file: test.csv


# Variables
# The variable we are attempting to predict (sale price)
target: DEATH_EVENT

pipeline_name: classification_model
pipeline_save_file: classification_model_output_v

features:
  - age
  - anaemia
  - diabetes
  - ejection_fraction
  - high_blood_pressure
  - serum_creatinine
  - serum_sodium
  - sex
  - time
# set train/test split
test_size: 0.2

# to set the random seed
random_state: 21

alpha: 0.001

n_jobs: -1
