repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.29.1
    hooks:
    -   id: pyupgrade
        args: [--py36-plus]
  - repo: https://github.com/psf/black
    rev: 21.9b0
    hooks:
      - id: black
        args: [--safe, --quiet]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: local
    hooks:
      - id: rst
        name: rst
        entry: rst-lint --encoding utf-8
        files: ^(CHANGELOG|README.rst)$
        language: python
        additional_dependencies: [pygments, restructuredtext_lint]
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v2.6.0
    hooks:
    - id: reorder-python-imports
      args: ['--application-directories=.:src']
