name: dev

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  dev-deps:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, windows-2019, macos-10.15]
        python-version: [3.6, "3.10"]

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: install developer dependencies
        run: pip install -r requirements.txt
