name: tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  canceller:
    runs-on: ubuntu-18.04
    steps:
      - name: cancel previous runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

  tests:

    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, windows-2019, macos-10.15]
        python-version: [3.6, "3.10"]
    env:
      OS: ${{ matrix.os }}
      PYTHON: ${{ matrix.python-version }}

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: install dependencies
        run: |
          pip install -r requirements/minimal.txt
          pip install -r requirements/tests.txt

      # Check that demes installs as expected.
      # Also check the "demes" CLI entry point.
      - name: install demes
        run: |
          pip install .
          demes -h

      - name: run pytest
        run: |
          python -m pytest -n auto \
            --cov=demes --cov-report=term-missing --cov-report=xml -v tests

      - name: upload coverage report to codecov
        uses: codecov/codecov-action@v2.1.0
        with:
          fail_ci_if_error: true
          env_vars: OS,PYTHON
