[tool.poetry]
name = "Gastepo"
version = "0.0.2"
description = "An base-on Schema DSL automation framework of Restful API."
authors = ["yuzhonghua <583512498@qq.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/bleiler1234/Gastepo"
documentation = "https://bleiler1234.github.io/Gastepo"
repository = "https://github.com/bleiler1234/gastepo"

keywords = ["schema", "dsl", "restful", "api", "test", "pytest", "allure", "pandas", "jsonpath", "hamcrest"]

classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Topic :: Software Development :: Testing",
    "Topic :: Software Development :: Quality Assurance",
    "Operating System :: MacOS",
    "Operating System :: POSIX :: Linux",
    "Operating System :: Microsoft :: Windows",
    "Programming Language :: Python :: 3.7"
]

[tool.poetry.dependencies]
python = "^3.7"
allure_python_commons = "^2.8.6"
allure_pytest = "^2.8.6"
pymongo = "^3.9.0"
xlrd = "^1.2.0"
colorlog = "^4.0.2"
openpyxl = "^3.0.0"
xlutils = "^2.0.0"
requests = "^2.22.0"
SQLAlchemy = "^1.3.9"
jsonpath = "^0.82"
xlwt = "^1.3.0"
rsa = "^4.0"
pandas = "^1.2.3"
retrying = "^1.3.3"
xmltodict = "^0.12.0"
pytest = "^5.3.2"
PyMySQL = "^0.9.3"
redis = "^3.5.3"
Flask = "^1.1.1"
pycryptodome = "^3.9.7"
PyHamcrest = "^2.0.2"
PyYAML = "^5.3.1"
fastapi = "^0.58.1"
uvicorn = "^0.11.5"
aiofiles = "^0.5.0"
jenkins = "^1.0.2"
emoji = "^1.2.0"
selenium = "^3.141.0"

[tool.poetry.dev-dependencies]
coverage = "^5.0.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[[tool.poetry.source]]
name = "aliyun"
url = "https://mirrors.aliyun.com/pypi/simple"
default = true

[tool.poetry.scripts]
gastepo = "gastepo.Cli:cli"
