[tool.poetry]
name = "artur_tancredo_alvarenga_puc_csv_converter"
version = "0.1.10"
description = "Trabalho da PUC - converter csv para json e json para csv"
authors = ["Artur <arturalvarenga@hotmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8.10"
pandas = "^1.3.4"
click = "^8.0.3"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
flake8 = "^4.0.1"
mypy = "^0.910"
black = "^21.10b0"
pandas-stubs = "^1.2.0"
ipython = "^7.29.0"
isort = "^5.10.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
#csv_converter = 'artur_tancredo_alvarenga_puc_csv_converter.converter_2:converter'
json_converter = 'artur_tancredo_alvarenga_puc_csv_converter.converter_2:converter_2'

[tool.black]
line-length = 99

[tool.isort]
profile = "black"