[tool.poetry]
name = "relevanceai-vectorops"
version = "0.1.2"
description = "Vector Ops Exploration and Tooling"
authors = ["Charlene Leong <charlene.leong@relevance.ai>"]
packages = [
    { include = "vectorops" }
]

[tool.poetry.dependencies]
python = ">=3.8,<3.10"
pandas = "^1.3.3"
scikit-learn = "^1.0"
scipy = "^1.7.1"
torch = "^1.9.1"
torchvision = "^0.10.1"
numpy = "^1.21.3"
plotly = "^5.3.1"
RelevanceAI = {extras = ["notebook"], version = "^0.17.0"}
document-utils = "^1.3.0"
vectorhub = {extras = ["text-encoder-transformers"], version = "^1.8.3"}


[tool.poetry.dev-dependencies]
peodd = "^0.3.0"
autopep8 = "^1.5.7"
click-log = "^0.3.2"
jupyter = "^1.0.0"
requests = "^2.26.0"
ipykernel = "^6.4.1"
ipywidgets = "^7.6.5"
widgetsnbextension = "^3.5.1"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
