name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag model_train:$(date +"%Y%m%d")
    - name: Run Tests
      run: docker run model_train:$(date +"%Y%m%d") "make test"
