[tool.poetry]
name = "pnprint"
version = "1.1"
description = "format and color serialized data strings, to make them more human readable"
authors = ["jimy byerley <jimy.byerley@gmail.com>"]
license = "GNU LGPL v3"

[tool.poetry.dependencies]
python = "^3.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
