[tool.poetry]
name = "django_svelte_married"
version = "0.0.8"
description = "JGM stands for \"Just-Got-Married\", because Django and Svelte is a perfect match 🤵👰."
authors = ["niespodd <dariusz@ticketwhat.pl>"]

[tool.poetry.dependencies]
python = ">=3.7"
requests = "^2.26.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
Django = ">=3.0.0"

[tool.poetry.scripts]
test = 'scripts:test'

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
