# ENGLISH: (Англиский)
# 
# CEO\Owner: vk.com/dan.owner & vk.com/dan.developer
# Produced by PyPi.org
# Module: pylibs
#
# RUSSIA: (Русский)
#
# Генеральный директор \ Владелец: vk.com/dan.owner & vk.com/dan.developer
# Произведено PyPi.org
# Модуль: pylibs
#

import os
import sys
print('+------------------------------------------------+')
print(' pylibs: Installing main modules for developers.')
print(' pylibs: Установка основных модулей для разработчиков.')
print('+------------------------------------------------+')

yes = ('Y')
no = ('n')

os.system('pip install time')
import time

time.sleep(3)

# Question for install (~53) modules.
general = input('Error. Permission denied.\nDo you really want to install 54 modules?\nТы правда хочешь установить 54 модуля?\n(Y \ n) --> ')
sys.hexversion
sys.hash_info
sys.float_info

if general == no:
	os.system('cls')
	print('Okay... Closing...\nОкей.... Закрытие....\n\n')
	exit()
	quit()

os.system('pip3 install time')
os.system('pip3 install gTTS')
os.system('pip3 install sTTgeo')
os.system('pip3 install sTTcv')
os.system('pip3 install MyAdmin')
os.system('pip3 install colorama')
os.system('pip3 install requests')
os.system('pip3 install discord')
os.system('pip3 install youtube-dl')
time.sleep(3)
print('aiohttp==3.7.4.post0')
print('async-timeout==3.0.1')
print('attrs==20.3.0')
print('certifi==2020.12.5')
time.sleep(3)
print('cffi==1.14.5')
print('chardet==4.0.0')
print('click==7.1.2')
print('csscompressor==0.9.5')
print('cycler==0.10.0')
print('discord.py==1.6.0')
print('Flask==1.1.2')
time.sleep(3)
print('google-images-download==2.8.0')
print('htmlmin==0.1.12')
print('idna==2.10')
print('inflection==0.5.1')
print('itsdangerous==1.1.0')
print('Jinja2==2.11.3')
print('joblib==1.0.0')
print('jsmin==2.2.2')
print('kiwisolver==1.3.1')
print('MarkupSafe==1.1.1')
time.sleep(3)
print('more-itertools==8.6.0')
print('multidict==5.1.0')
print('mysql-connector-python==8.0.23')
print('numpy==1.19.5')
print('pandas==1.2.1')
print('Pillow==8.1.0')
print('protobuf==3.15.6')
print('pycparser==2.20')
print('pygame==2.0.1')
print('PyNaCl==1.4.0')
print('pyparsing==2.4.7')
time.sleep(3)
print('python-dateutil==2.8.1')
print('pytz==2020.5')
print('Quandl==3.6.0')
print('requests==2.25.1')
print('scipy==1.6.0')
print('selenium==3.141.0')
print('six==1.15.0')
time.sleep(3)
print('threadpoolctl==2.1.0')
print('typing-extensions==3.7.4.3')
print('urllib3==1.26.2')
print('Werkzeug==1.0.1')
print('yarl==1.6.3')
print('youtube-dl==2021.3.14')
time.sleep(3)
os.system('pip install aiohttp==3.7.4.post0')
os.system('pip install async-timeout==3.0.1')
os.system('pip install attrs==20.3.0')
os.system('pip install certifi==2020.12.5')
os.system('pip install cffi==1.14.5')
os.system('pip install chardet==4.0.0')
os.system('pip install click==7.1.2')
time.sleep(3)
os.system('pip install csscompressor==0.9.5')
os.system('pip install cycler==0.10.0')
os.system('pip install discord.py==1.6.0')
os.system('pip install Flask==1.1.2')
os.system('pip install google-images-download==2.8.0')
os.system('pip install htmlmin==0.1.12')
os.system('pip install idna==2.10')
time.sleep(3)
os.system('pip install inflection==0.5.1')
os.system('pip install itsdangerous==1.1.0')
os.system('pip install Jinja2==2.11.3')
os.system('pip install joblib==1.0.0')
os.system('pip install jsmin==2.2.2')
time.sleep(3)
os.system('pip install kiwisolver==1.3.1')
os.system('pip install MarkupSafe==1.1.1')
os.system('pip install more-itertools==8.6.0')
os.system('pip install multidict==5.1.0')
os.system('pip install mysql-connector-python==8.0.23')
os.system('pip install numpy==1.19.5')
os.system('pip install pandas==1.2.1')
time.sleep(3)
os.system('pip install pip install Pillow==8.1.0')
os.system('pip install pip install protobuf==3.15.6')
os.system('pip install pip install pycparser==2.20')
os.system('pip install pip install pygame==2.0.1')
os.system('pip install pip install PyNaCl==1.4.0')
time.sleep(3)
os.system('pip install pip install pyparsing==2.4.7')
os.system('pip install pip install python-dateutil==2.8.1')
os.system('pip install pip install pytz==2020.5')
os.system('pip install pip install Quandl==3.6.0')
os.system('pip install pip install requests==2.25.1')
os.system('pip install pip install scipy==1.6.0')
os.system('pip install pip install selenium==3.141.0')
os.system('pip install pip install six==1.15.0')
time.sleep(3)
os.system('pip install pip install threadpoolctl==2.1.0')
os.system('pip install pip install typing-extensions==3.7.4.3')
os.system('pip install pip install urllib3==1.26.2')
os.system('pip install pip install Werkzeug==1.0.1')
os.system('pip install pip install yarl==1.6.3')
os.system('pip install pip install youtube-dl==2021.3.14')

confirm = input('Error. Permission denied!\nFinish installation?\nЗакончить установку?\n(Y \ n) --> ')

if confirm == no:
	os.system('cls')
	print('Okay... Deleting all changes...\nОкей.... Удаление всех изменений....\n\n')
	os.system('pip unistall aiohttp==3.7.4.post0')
	os.system('pip unistall async-timeout==3.0.1')
	os.system('pip unistall attrs==20.3.0')
	os.system('pip unistall certifi==2020.12.5')
	time.sleep(3)
	os.system('pip unistall cffi==1.14.5')
	os.system('pip unistall chardet==4.0.0')
	os.system('pip unistall click==7.1.2')
	os.system('pip unistall csscompressor==0.9.5')
	os.system('pip unistall cycler==0.10.0')
	os.system('pip unistall discord.py==1.6.0')
	os.system('pip unistall Flask==1.1.2')
	os.system('pip unistall google-images-download==2.8.0')
	os.system('pip unistall htmlmin==0.1.12')
	time.sleep(3)
	os.system('pip unistall idna==2.10')
	os.system('pip unistall inflection==0.5.1')
	os.system('pip unistall itsdangerous==1.1.0')
	os.system('pip unistall Jinja2==2.11.3')
	os.system('pip unistall joblib==1.0.0')
	os.system('pip unistall jsmin==2.2.2')
	os.system('pip unistall kiwisolver==1.3.1')
	time.sleep(3)
	os.system('pip unistall MarkupSafe==1.1.1')
	os.system('pip unistall more-itertools==8.6.0')
	os.system('pip unistall multidict==5.1.0')
	os.system('pip unistall mysql-connector-python==8.0.23')
	os.system('pip unistall numpy==1.19.5')
	os.system('pip unistall pandas==1.2.1')
	os.system('pip unistall pip unistall Pillow==8.1.0')
	time.sleep(3)
	os.system('pip unistall pip unistall protobuf==3.15.6')
	os.system('pip unistall pip unistall pycparser==2.20')
	os.system('pip unistall pip unistall pygame==2.0.1')
	os.system('pip unistall pip unistall PyNaCl==1.4.0')
	os.system('pip unistall pip unistall pyparsing==2.4.7')
	os.system('pip unistall python-dateutil==2.8.1')
	os.system('pip unistall pytz==2020.5')
	time.sleep(3)
	os.system('pip unistall Quandl==3.6.0')
	os.system('pip unistall requests==2.25.1')
	os.system('pip unistall scipy==1.6.0')
	os.system('pip unistall selenium==3.141.0')
	os.system('pip unistall six==1.15.0')
	os.system('pip unistall threadpoolctl==2.1.0')
	time.sleep(3)
	os.system('pip unistall typing-extensions==3.7.4.3')
	os.system('pip unistall urllib3==1.26.2')
	os.system('pip unistall Werkzeug==1.0.1')
	os.system('pip unistall yarl==1.6.3')
	os.system('pip unistall youtube-dl==2021.3.14')
	print('Complete! All changes was removed!\nУспешно! Все изменения были удалены!\n\n')
	time.sleep(5)
	exit()
	quit()

print('Success! All installed!\nУспешно! Все установлено!\n\n')
time.sleep(5)
