[tool.poetry]
authors = ["Kevin Pressouyre <kevin.pressouyre@gmail.com>"]
classifiers = [
  "License :: OSI Approved :: Apache Software License",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.6",
  "Programming Language :: Python :: 3.7",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Topic :: System :: Networking",
]
description = "Akamai plugins for Nornir"
documentation = "https://github.com/kpressouyre/nornir_akamai"
homepage = "https://github.com/kpressouyre/nornir_akamai"
keywords = ["nornir", "akamai", "automation"]
license = "Apache-2.0"
name = "nornir_akamai"
readme = "README.md"
repository = "https://github.com/kpressouyre/nornir_akamai"
version = "0.0.1"

[tool.poetry.urls]
Issues = "https://github.com/kpressouyre/nornir_akamai/issues"
"Pull Requests" = "https://github.com/kpressouyre/nornir_akamai/pulls"
Releases = "https://github.com/kpressouyre/nornir_akamai/releases"

[tool.poetry.dependencies]
edgegrid-python = "^1.2.1"
nornir = "^3.0.0"
packaging = "^20.9"
python = "^3.6"
requests-toolbelt = "^0.9.1"
urllib3 = "^1.26.3"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
coverage = "^5.4"
darglint = "^1.6.0"
flake8 = "^3.8.4"
flake8-bandit = "^2.1.2"
flake8-black = "^0.2.1"
flake8-bugbear = "^20.11.1"
flake8-builtins = "^1.5.3"
flake8-comprehensions = "^3.3.1"
flake8-docstrings = "^1.5.0"
flake8-eradicate = "^1.0.0"
flake8-isort = "^4.0.0"
flake8-pytest-style = "^1.3.0"
flake8-requirements = "^1.3.3"
nornir-utils = "^0.1.1"
pep8-naming = "^0.11.1"
pytest = "^6.2.2"
responses = "^0.12.1"

[tool.poetry.plugins."nornir.plugins.connections"]
"akamai" = "nornir_akamai.plugins.connections:AkamaiRestClient"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]

[tool.black]
exclude = '''
/(
  | \.git
  | \.github
  | \.idea
  | \.pytest_cache
  | \.venv
  | \.vscode
  | __pycache__
  | htmlcov
)/
'''
include = '\.pyi?$'
line-length = 88
target-version = ['py36']

[tool.coverage.run]
branch = true
source = ["nornir_eip"]

[tool.coverage.report]
fail_under = 100
show_missing = true

[tool.isort]
profile = "black"
src_paths = ["nornir_eip", "tests"]

[tool.pytest.ini_options]
addopts = "-ra -q"
minversion = "6.0"
testpaths = ["tests"]