[tool.poetry]
name = "djaxei"
version = "0.7.0"
description = "A django admin extension for importing exporting records from/to xls/ods"
authors = ["Giovanni Bronzini <g.bronzini@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/GigiusB/djaxei.git"
keywords = ["xls",]
include = ["README.md", "HISTORY.md", "Makefile"]
packages = [
    { include = "djaxei", from = "src" },
]

[tool.poetry.dependencies]
python = ">=3.6.1,<4"
django = ">=1.11,<4"
openpyxl = { version = "<4", optional = true }
xlwt = {version = ">=1.2.0", optional = true}
xlsxwriter = {version = ">=1.2.8", optional = true}

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
tox = "^3.24.4"
pytest-django = "^4.5.2"
factory-boy = "^3.2.1"
pytest-pythonpath = "^0.7.3"
flake8 = "^4.0.1"
isort = "^5.10.1"
django-webtest = "^1.9.8"
pytest-env = "^0.6.2"
pytest-coverage = "^0.0"
pytest-echo = "^1.7.1"

[tool.poetry.extras]
openpyxl = ["openpyxl"]
xlsxwriter = ["xlsxwriter"]
xlwt = ["xlwt"]

#requires = ["poetry>=1.1"]
#build-backend = "poetry.masonry.api"
[build-system]
requires = [
    "setuptools >= 35.0.2",
    "setuptools_scm >= 2.0.0, <3"
]
build-backend = "setuptools.build_meta"