[package]
name = "DeepFilterDataLoader"
version = "0.1.9"
authors = ["Hendrik Schröter <h.schroeter@pm.me>"]
edition = "2021"

[lib]
name = "libdfdata"
crate-type = ["cdylib"]
path = "src/lib.rs"

[dependencies]
deep_filter = { features = ["dataset"], version = "0.1.9" }
pyo3 = { version = "^0.15", default_features = true, features = ["extension-module"]}
numpy = "^0.15"
ndarray = "^0.15"
