[tool.poetry]
name = "csv_converter_valtensir"
version = "0.1.2"
description = "A project to converter JSON to CSV and CSV to JSON files."
authors = ["Valtensir Lopes <valtensirl@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
click = "^8.0.3"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
black = "^21.11b1"
flake8 = "^4.0.1"
mypy = "^0.910"
isort = "^5.10.1"
ipython = "^7.30.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-lenght=99

[tool.isort]
profile="black"

[tool.poetry.scripts]
csv_converter = 'csv_converter_valtensir.converter:converter'