[tool.poetry]
name = "triangler-patch"
version = "0.1.0"
description = ""
packages = [{ include = "triangler"}]
authors = ["djkcyl <cyl@cyllive.cn>"]

[tool.poetry.dependencies]
python = "3.9"
numba = "^0.54.1"
scikit-image = "^0.19.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[[tool.poetry.source]]
name = "tsinghua"
url = "https://pypi.tuna.tsinghua.edu.cn/simple"
default = true
