[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 80
skip-string-normalization = true

[tool.isort]
skip = "migrations"
include_trailing_comma = true
multi_line_output = 3
lines_after_imports = 2
default_section = "THIRDPARTY"
sections = "FUTURE, STDLIB, THIRDPARTY, DJANGO, FIRSTPARTY, LOCALFOLDER"
known_first_party = "zweifach"
known_django = "django"
line_length = 80
