[tool.poetry]
name = "sumo_output_parsers"
version = "0.51"
description = "Fast and lightweight file parsers for SUMO(traffic simulator) output"
authors = ["Kensuke Mitsuzawa <kensuke.mit@gmail.com>"]
maintainers = ["Kensuke Mitsuzawa <kensuke.mit@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.7"
dataclasses = "*"
nptyping = "^1.4.1"
numpy = "*"
scikit-learn = "*"
scipy = "*"
Cython = "*"
h5py = "*"
tabulate = "*"
pandas = "*"
tqdm = "^4.61.2"
more_itertools = "*"
requests = "*"
joblib = "*"
hvplot = "*"
lxml = "*"

moviepy = { version = "<1.0.2", optional = true }
Shapely = { version = "^1.7.0", optional = true }
pyproj = { version = "^3.0.0", optional = true }
SumoNetVis = { version = "^1.6.0", optional = true }
geopandas = { version = "^0.10.0", optional = true }
geoviews = { version = "^1.9.1", optional = true }
Cartopy = { version = "^0.18.0", optional = true }
imageio-ffmpeg = { version = "*", optional = true }
pyviz = { version = "*", optional = true }

[tool.poetry.dev-dependencies]
pytest = "^6.2.3"
pytest-resource-path = "^1.3.0"
nbmake = "0.5"
pytest-parallel = "*"
sphinx = "*"

[tool.poetry.scripts]

[build-system]
requires = ["setuptools", "poetry", "poetry_core>=1.0", "cython"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.extras]
full = ["Shapely", "pyproj", "SumoNetVis", "geopandas", "geoviews", "imageio-ffmpeg", "pyviz", "moviepy"]
