[build-system]
requires = [
    "maturin==0.11.2",

    # rasterio is only needed for the unittests
    "rasterio>=1.1"
]
build-backend = "maturin"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "--doctest-modules -v -s"
testpaths = [
    "h3ronpy",
    "tests"
]
