[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "cython",
    "scikit-build>=0.12",
    "cmake"
]

build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
markers = [
    "eda: this test requires EDA tools installed to run. By default these tests will be run nightly, not on push.",
    "quick: always run this test on push, even if it requires EDA tools."
]
testpaths = "tests"
