[tool.poetry]
name = "dj-qiyu-tpl"
version = "0.5.0"
description = "Template for internal use"
homepage = "https://www.qiyutech.tech/"
authors = ["dev <dev@qiyutech.tech>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"

django = ">=3.2.10,<4.0"

# 第三方依赖
docutils = ">=0.17,<0.19"
pygments = ">=2.8,<3.0"

django-qiyu-utils = ">=0.3.9,<0.4"

[tool.poetry.dev-dependencies]
black = "*"
pytest = "*"
pytest-django = "*"
pylama = "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
