[tool.poetry]
name = "cryptovwap"
version = "0.1.3"
description = ""
authors = ["Pablo Manso <92manso@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
dash = "^2.0.0"
pandas = "^1.3.4"
krakenex = "^2.1.0"
pykrakenapi = "^0.2.3"
python-bitvavo-api = "^1.2.2"
twine = "^3.7.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
cryptovwap = "cryptovwap.cli:main"