[tool.poetry]
authors = ["Joao Corte <jpaulorc@gmail.com>"]
description = "Convert csv to json and json to csv. Publishin only for leaning purposes."
exclude = ["jpaulorc_csv_converter/.git"]
name = "jpaulorc_csv_converter"
readme = "README.md"
version = "0.1.2"

[tool.poetry.dependencies]
click = "^8.0.3"
python = "^3.9"

[tool.poetry.dev-dependencies]
black = "^21.12b0"
flake8 = "^4.0.1"
ipython = "^7.30.1"
isort = "^5.10.1"
mypy = "^0.910"
pytest = "^5.2"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]

[tool.poetry.scripts]
csv_converter = 'jpaulorc_csv_converter.converter:converter'

[tool.black]
line-length = 99

[tool.isort]
profile = "black"
