[tool.poetry]
name = "dsi-cookbook"
version = "0.1.1"
description = "The only cookbook you'll ever need"
authors = ["Qiushi Yan <qiushi.yann@gmail.com>"]
readme = "readme.md"

[tool.poetry.scripts]
dsi-cookbook = "dsi_cookbook.main:app"

[tool.poetry.dependencies]
python = "^3.6"
typer = "^0.3.0"
typer-cli = "^0.0.12"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
