[build-system]
requires = ["setuptools >=42", "wheel", "setuptools_scm[toml] >=3.4"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]

[tool.black]
line-length = 80
skip-string-normalization = true

[tool.isort]
profile = 'black'
line_length = 80
known_first_party = 'vmail'
sections = [
  'FUTURE', 'STDLIB', 'THIRDPARTY', 'FIRSTPARTY', 'LOCALFOLDER'
]
