[tool.poetry]
name = "bhoelHelper"
version = "1.2.2"
description = "Misc helper functionalities."
packages = [{ include = "berhoel" }]
exclude = ["**/.#*.py", "**/#*.py#"]
authors = ["Berthold Höllmann <berhoel@gmail.com>"]
license = "MIT"
repository = "https://gitlab.com/berhoel/python/bhoelHelper.git"
homepage = "https://python.xn--hllmanns-n4a.de/bhoelHelper/"
documentation = "https://www.xn--hllmanns-n4a.de/python/bhoelHelper/"
readme = "README.rst"
classifiers = [
  "Development Status :: 5 - Production/Stable",
  "Topic :: Utilities",
]

[tool.poetry.dependencies]
python = ">3.6,<4.0"
sphinx_bootstrap_theme = "*"

[tool.poetry.dev-dependencies]
pytest = "*"
tox = "*"
pdbpp = "*"
Sphinx = "*"
sphinx-rtd-theme = "*"
blacker = "*"
flake8 = "*"
pylint = "*"
rope = "*"
numpydoc = "*"
urllib3 = "^1.26.7"

[tool.isort]
multi_line_output = 5
include_trailing_comma = true
indent = '    '
length_sort = true
line_length = 88
balanced_wrapping = true
import_heading_stdlib = 'Standard libraries.'
import_heading_thirdparty = 'Third party libraries.'
known_first_party = ['berhoel']

[tool.pytest.ini_options]
addopts = "--doctest-modules --ff --pdb -s"

[flake8]
max-line-length = 88

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
