# This file automatically generated by
#    C:\Jenkins\workspace\python\sdk\test-scripted-build-pipeline\couchbase-python-client\couchbase_version.py
# at
#    2021-12-07 09:40:10.025447
__version__ = '3.2.4'