BACKGROUNDDATA = {
    # To be expanded upon
    # "background_name": {
    #     "skills": [],
    #     "details": [],
    #     "traits": [],
    #     "ideals": [],
    #     "bonds": [],
    #     "flaws": [],
    # },
    "Acolyte": {
        "skills": ["Insight", "Religion"],
        "details": [
            "I wear the gauntlet of Helm, god of protection",
            "I wear the snowflake of Auril, goddess or winter.",
            "I wear the black antlers of Beshaba, goddess of misfortune.",
            "I wear the clawed paw of Mahar, god of the hunt.",
            "I wear the blank scroll of Oghma, god of knowledge.",
            "I wear the bolt of Talos, god of storms.",
            "I wear the red cord of Ilmatet, god of endurance.",
            "I wear the harp of Milel, god of songs.",
        ],
        "traits": [
            "I idolize a particular hero of my faith, and constantly",
            "refer to that person's deeds and example.",
            " I can find common ground between the fiercest enemies, empathizing with them and always working toward peace.",
            " I see omens in every event and action. The gods try to speak to us, we just need to listen.",
            " Nothing can shake my optimistic attitude.",
            " I quote (or misquote) sacred texts and proverbs in almost every situation.",
            " I am tolerant (or intolerant) of other faiths and respect (or condemn) the worship ofother gods.",
            " I've enjoyed fine food, drink, and high society among my temple's elite. Rough living grates on me.",
            " I've spent so long in the temple that I have little practical experience dealing with people in the outside world.",
        ],
        "ideals": [
            "Tradition. The ancient traditions of worship and sacrifice must be preserved and upheld. (Lawful)",
            "Charity. I always try to help those in need, no matter what the personal cost. (Good)",
            "Change. We must help bring about the changes the gods are constantly working in the world. (Chaotic)",
            "Power. I hope to one day rise to the top of my faith's religious hierarchy. (Lawful)",
            "Faith. I trust that my deity will guide my actions. I have faith that if I work hard, things will go well. (Lawful)",
            "Aspiration. I seek to prove myself worthy of my god's favor by matching my actions against his or her teachings. (Any)",
        ],
        "bonds": [
            "I would die to recover an ancient relic of my faith that",
            "was lost long ago.",
            "I will someday get revenge on the corrupt temple hierarchy who branded me a heretic.",
            "I owe my life to the priest who took me in when my",
            "parents died.",
            "Everything I do is for the common people.",
            "I will do anything to protect the temple where I served. 6 I seek to preserve a sacred text that my enemies",
            "consider heretical and seek to destroy.",
        ],
        "flaws": [
            "I judge others harshly, and myself even more severely.",
            "I put too much trust in those who wield power within my temple's hierarchy.",
            "My piety sometimes leads me to blindly trust those that profess faith in my god.",
            "I am inflexible in my thinking.",
            "I am suspicious of strangers and expect the worst of them.",
            "Once I pick a goal, I become obsessed with it to the detriment ofeverything else in my life.",
        ],
    },
    "Criminal": {
        "skills": ["Deception", "Stealth"],
        "details": [
            "Blackmailer",
            "Burglar",
            "Enforcer",
            "Fence",
            "Highway robber",
            "Hired killer",
            "Pickpocket",
            "Smuggler",
        ],
        "traits": [
            "I always have a plan for what to do when things go wrong.",
            "I am always calm, no matter what the situation. I never raise my voice or let my emotions control me.",
            "The first thing I do in a new place is note the locations ofeverything valuable-or where such things could be hidden.",
            "I would rather make a new friend than a new enemy.",
            "I am incredibly slow to trust. Those who seem the fairest often have the most to hide.",
            "I don't pay attention to the risks in a situation. Never tell me the odds.",
            "The best way to get me to do something is to tell me I can't do it.",
            "I blow up at the slightest insult.",
        ],
        "ideals": [
            "Honor. I don't steal from others in the trade. (Lawful)",
            "Freedom. Chains are meant to be broken, as are those who would forge them. (Chaotic)",
            "Charity. I steal from the wealthy so that I can help people in need. (Good)",
            "Greed. I will do whatever it takes to become wealthy. (Evil)",
            "People. I'm loyal to my friends, not to any ideals, and everyone else can take a trip down the Styx for all I care. (Neutral)",
            "Redemption. There's a spark of good in everyone. (Good)",
        ],
        "bonds": [
            "I'm trying to pay off an old debt I owe to a generous benefactor.",
            "My ill-gotten gains go to support my family.",
            "Something important was taken from me, and I aim tosteal it back.",
            "I will become the greatest thief that ever lived.",
            "I'm guilty of a terrible crime. I hope I can redeem myself for it.",
            "Someone I loved died because of I mistake I made. That will never happen again.",
        ],
        "flaws": [
            "When I see something valuable, I can't think about anything but how to steal it.",
            "When faced with a choice between money and my friends, I usually choose the money.",
            "If there's a plan, I'll forget it. If I don't forget it, I'II ignore it.",
            'I have a "tell" that reveals when I\'m lying.',
            "I turn tail and run when things look bad.",
            "An innocent person is in prison for a crime that I committed. I'm okay with that.",
        ],
    },
    "Outlander": {
        "skills": ["Athletics", "Survival"],
        "details": [
            "Forester",
            "Trapper",
            "Homesteader",
            "Bounty hunter",
            "Pilgrim",
            "Tribal nomad",
            "Bounty hunter",
            "Pilgrim",
            "Tribal nomad",
            "Guide",
            "Exile",
            "Hunter-gatherer",
            "Tribal marauder",
        ],
        "traits": [
            "I'm driven by a wanderlust that led me away from home.",
            "I watch over my friends as ifthey were a litter of newborn pups.",
            "I once ran twenty-five miles without stopping to warn to my clan ofan approaching ore horde. I'd do it again ifIhadto.",
            "I have a lesson for every situation, drawn from observing nature.",
            "I place no stock in wealthy or well-mannered folk. Money and manners won't save you from a hungry owlbear.",
            "I'm always picking things up, absently fiddling with them, and sometimes accidentally breaking them.",
            "I feel far more comfortable around animals than people.",
            "I was, in fact, raised by wolves.",
        ],
        "ideals": [
            "Change. Life is like the seasons, in constant change, and we must change with it. (Chaotic)",
            "Greater Good. It is each person's responsibility to make the most happiness for the whole tribe. (Good)",
            "Honor. If I dishonor myself, I dishonor my whole clan. (Lawful)",
            "Might. The strongest are meant to rule. (Evil)",
            "Nature. The natural world is more important than all the constructs ofcivilization. (Neutral)",
            "Glory. I must earn glory in battle, for myself and my clan. (Any)",
        ],
        "bonds": [
            "My family, clan, or tribe is the most important thing in my life, even when they are far from me.",
            "An injury to the unspoiled wilderness ofmy home is an injuryto me.",
            "I will bring terrible wrath down on the evildoers who destroyed my homeland.",
            "I am the last of my tribe, and it is up to me to ensure their names enter legend.",
            "I suffer awful visions ofa coming disaster and will do anything to prevent it.",
            "It is my duty to provide children to sustain my tribe.",
        ],
        "flaws": [
            "I am too enamored ofale, wine, and other intoxicants.",
            "There's no room for caution in a life lived to the fullest.",
            "I remember every insult I've received and nurse a silent resentment toward anyone who's ever wronged me.",
            "I am slow to trust members ofother races, tribes, and societies.",
            "Violence is my answer to almost any challenge.",
            "Don't expect me to save those who can't save themselves. It is nature's way that the strong thrive and the weak perish.",
        ],
    },
}
