from ..stats import Stats

RACEDATA = {
    # To be expanded upon
    # "race_name": {
    #     "first_name": [],
    #     "last_name": [],
    #     "speed": 30,
    #     "subraces": {
    #         "subrace_name": {
    #             "stats_mod": Stats(),
    #         }
    #     },
    # }
    "Dwarf": {
        "first_name": [
            "Adrik",
            "Alberich",
            "Baern",
            "Barendd",
            "Brottor",
            "Bruenor",
            "Dain",
            "Darrak",
            "Delg",
            "Eberk",
            "Einkil",
            "Fargrim",
            "Flint",
            "Gardain",
            "Harbek",
            "Kildrak",
            "Morgran",
            "Orsik",
            "Oskar",
            "Rangrim",
            "Rurik",
            "Taklinn",
            "Thoradin",
            "Thorin",
            "Tordek",
            "Traubon",
            "Travok",
            "Ulfgar",
            "Veit",
            "Vonda",
            "Amber",
            "Artin",
            "Audhild",
            "Bardryn",
            "Dagnal",
            "Diesa",
            "Eldeth",
            "Falkrunn",
            "Finellen",
            "Gunnloda",
            "Gurdis",
            "Helja",
            "Hlin",
            "Kathra",
            "Kristryd",
            "Ilde",
            "Liftrasa",
            "Mardred",
            "Riswynn",
            "Sann!",
            "Torbera",
            "Torgga",
            "Vistra",
        ],
        "last_name": [
            "Balderk",
            "Battlehammer",
            "Brawnanvil",
            "Dankil",
            "Fireforge",
            "Frostbeard",
            "Gorunn",
            "Holderhek",
            "Ironfist",
            "Loderr",
            "Lutgehr",
            "Rumnaheim",
            "Strakeln",
            "Torunn",
            "Ungart",
        ],
        "speed": 25,
        "subraces": {
            "Hill Dwarf": {
                "stats_mod": Stats(CON=2, WIS=1),
            },
            "Mountain Dwarf": {"stats_mod": Stats(CON=2, STR=2)},
        },
    },
    "Elf": {
        "first_name": [
            "Ara",
            "Bryn",
            "Del",
            "Eryn",
            "Faen",
            "Innil",
            "Lael",
            "Mella",
            "Naill",
            "Naeris",
            "Phann",
            "Rael",
            "Rinn",
            "Sai",
            "Syllin",
            "Thia",
            "Vall",
            "Adran",
            "Aelar",
            "Aramil",
            "Arannis",
            "Aust",
            "Beiro",
            "Berrian",
            "Carrie",
            "Enialis",
            "Erdan",
            "Erevan",
            "Galinndan",
            "Hadarai",
            "Heian",
            "Himo",
            "Immeral",
            "Ivellios",
            "Laucian",
            "Mindartis",
            "Paelias",
            "Peren",
            "Quarion",
            "Riardon",
            "Rolen",
            "Soveliss",
            "Thamior",
            "Tharivol",
            "Theren",
            "Varis",
            "Adrie",
            "Althaea",
            "Anastrianna",
            "Andraste",
            "Antinua",
            "Bethrynna",
            "Birel",
            "Caelynn",
            "Drusilia",
            "Enna",
            "Felosial",
            "Ielenia",
            "Jelenneth",
            "Keyleth",
            "Leshanna",
            "Lia",
            "Meriele",
            "Mialee",
            "Naivara",
            "Quelenna",
            "Quillathe",
            "Sariel",
            "Shanairra",
            "Shava",
            "Silaqui",
            "Theirastra",
            "Thia",
            "Vadania",
            "Valanthe",
            "Xanaphia",
        ],
        "last_name": [
            "Amakiir (Gemflower)",
            "Amastacia (Starflower)",
            "Galanodel (Moonwhisper)",
            "Holimion (Diamonddew)",
            "Ilphelkiir (Gemblossom)",
            "Liadon (Silverfrond)",
            "Meliamne (Oakenheel)",
            "Nallo (Nightbreeze)",
            "Siannodel (Moonbrook)",
            "Xiloscient (Goldpetal)",
        ],
        "speed": 30,
        "subraces": {
            "High Elf": {
                "stats_mod": Stats(DEX=2, INT=1),
            },
            "Wood Elf": {
                "stats_mod": Stats(DEX=2, WIS=1),
            },
            "Drow": {
                "stats_mod": Stats(DEX=2, CHA=1),
            },
        },
    },
    "Human": {
        "first_name": [
            "Aseir",
            "Bardeid",
            "Haseid",
            "Khemed",
            "Mehmen",
            "Sudeiman",
            "Zasheir",
            "Atala",
            "Ceidil",
            "Hama",
            "jasmal",
            "Meilil",
            "Seipora",
            "Yasheira",
            "Zasheida",
            "Darvin",
            "Dorn",
            "Evendur",
            "Gorstag",
            "Grim",
            "Helm",
            "Malark",
            "Morn",
            "Randal",
            "Stedd",
            "Arveene",
            "Esvele",
            "Jhessail",
            "Kerri",
            "Lureene",
            "Miri",
            "Rowan",
            "Shandri",
            "Tessele",
        ],
        "last_name": [
            "Basha",
            "Dumein",
            "Jassan",
            "Khalid",
            "Mostana",
            "Pashar",
            "Rein",
            "Amblecrown",
            "Buckman",
            "Dundragon",
            "Evenwood",
            "Greycastle",
            "Tallstag",
        ],
        "speed": 30,
        "subraces": {
            "Calishite": {
                "stats_mod": Stats(STR=1, DEX=1, WIS=1, INT=1, CHA=1, CON=1),
            },
            "Damaran": {
                "stats_mod": Stats(STR=1, DEX=1, WIS=1, INT=1, CHA=1, CON=1),
            },
        },
    },
    "Tiefling": {
        "first_name": [
            "Akmenos",
            "Amnon",
            "Barakas",
            "Damakos",
            "Ekemon",
            "Iados",
            "Kairon",
            "Leucis",
            "Melech",
            "Mordai",
            "Morthos",
            "Pelaios",
            "Skamos",
            "Therai",
            "Akta",
            "Anakis",
            "Bryseis",
            "Criella",
            "Damaia",
            "Ea",
            "Kallista",
            "Lerissa",
            "Makaria",
            "Nemeia",
            "Orianna",
            "Phelaia",
            "Rieta",
        ],
        "last_name": [
            "Art",
            "Carrion",
            "Chant",
            "Creed",
            "Despair",
            "Excellence",
            "Fear",
            "Glory",
            "Hope",
            "Ideal",
            "Music",
            "Nowhere",
            "Open",
            "Poetry",
            "Quest",
            "Random",
            "Reverence",
            "Sorrow",
            "Temerity",
            "Torment",
            "Weary",
        ],
        "speed": 30,
        "subraces": {
            "Tiefling": {
                "stats_mod": Stats(INT=1, CHA=2),
            },
        },
    },
    "Half-Orc": {
        "first_name": [
            "Dench",
            "Feng",
            "Gell",
            "Henk",
            "Holg",
            "Imsh",
            "Keth",
            "Krusk",
            "Mhurren",
            "Ront",
            "Shump",
            "Thokk",
            "Baggi",
            "Emen",
            "Engong",
            "Kansif",
            "Myev",
            "Neega",
            "Ovak",
            "Ownka",
            "Shautha",
            "Sutha",
            "Vola",
            "Volen",
            "Yevelda",
        ],
        "last_name": [""],
        "speed": 30,
        "subraces": {
            "Half-Orc": {
                "stats_mod": Stats(STR=2, CON=1),
            }
        },
    },
    "Gnome": {
        "first_name": [
            "Alston",
            "Alvyn",
            "Boddynock",
            "Broce",
            "Burgell",
            "Dimble",
            "Eldon",
            "Erky",
            "Fonkin",
            "Frug",
            "Gerbo",
            "Gimble",
            "Glim",
            "Jebeddo",
            "Kellen",
            "Namfoodle",
            "Orryn",
            "Roondar",
            "Seebo",
            "Sindri",
            "Warryn",
            "Wrenn",
            "Zook",
            "Bimpnottin",
            "Breena",
            "Caramip",
            "Carlin",
            "Donella",
            "Duvamil",
            "Ella",
            "Ellyjobell",
            "Ellywick",
            "Lilli",
            "Loopmottin",
            "Lorilla",
            "Mardnab",
            "Nissa",
            "Nyx",
            "Oda",
            "Orla",
            "Roywyn",
            "Shami!",
            "Tana",
            "Waywocket",
            "Zanna",
            "Aleslosh",
            "Ashhearth",
            "Badger",
            "Cloak",
            "Doublelock",
            "Filchbatter",
            "Fnipper",
            "Ku",
            "Nim",
            "Oneshoe",
            "Pock",
            "Sparklegem",
            "Stumbleduck",
        ],
        "last_name": [
            "Beren",
            "Daergel",
            "Folkor",
            "Garrick",
            "Nackle",
            "Murnig",
            "Ningel",
            "Raulnor",
            "Scheppen",
            "Timbers",
            "Turen",
        ],
        "speed": 30,
        "subraces": {
            "Forest Gnome": {
                "stats_mod": Stats(INT=2, DEX=1),
            },
            "Rock Gnome": {
                "stats_mod": Stats(INT=2, CON=1),
            },
        },
    },
}
